organizational_units:
  Audit:
    parent_id: "r-xxxx"  # Replace with your org root ID
    accounts:
      - name: "Audit"
        email: "your-audit-email@domain.com"
      - name: "Log Archive"
        email: "your-logarchive-email@domain.com"

  Workload:
    parent_id: "r-xxxx"  # Replace with your org root ID
    accounts:
      - name: "Prod-Workload"
        email: "your-prod-email@domain.com"
      - name: "conneft"
        email: "your-conneft-email@domain.com"
