AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Organizations Service Control Policies'

Resources:
  DenyRootAccess:
    Type: AWS::Organizations::Policy
    Properties:
      Content: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "DenyRootAccess",
              "Effect": "Deny",
              "Action": "*",
              "Resource": "*",
              "Condition": {
                "StringLike": {
                  "aws:PrincipalArn": "arn:aws:iam::*:root"
                }
              }
            }
          ]
        }
      Name: DenyRootAccess
      Type: SERVICE_CONTROL_POLICY
